### ISSUE TITLE
model Yi-34B-Chat output a lot [/INST]  <|im_end|>

### ISSUE THREAD

**Issue by goldenquant** [vectorch-ai/ScaleLLM#23]
using docker-compose ,chat in ChatBot UI,output like this:

![image](https://github.com/vectorch-ai/ScaleLLM/assets/108568777/02e6a0f8-36a6-4c31-a628-2fbd7b3da76d)

**Comment by guocuimi** [comment]
Thanks for using ScaleLLM. 
Sounds you are using wrong chat template for Yi model. `<|im_end|>` is the stop token for Yi model.
Adding '--model_type=Yi` to the command would fix it.
```
scalellm:
    image: vectorchai/scalellm:latest
    hostname: scalellm
    container_name: scalellm
    ports:
      - 8888:8888
      - 9999:9999
    environment:
      - HF_MODEL_ID=${HF_MODEL_ID:-TheBloke/Llama-2-7B-chat-AWQ}
      ......
    volumes:
      - $HOME/.cache/huggingface/hub:/models
    shm_size: 1g
    command: --logtostderr --model_type=Yi
```

Some background, Yi and Llama share the same [model architecture](https://huggingface.co/01-ai/Yi-34B-Chat/blob/main/config.json#L13) but use different chat template. In order to use right chat template, we need to explicitly tell ScaleLLM by setting '--model_type=Yi`.
