### ISSUE TITLE
scalellm exited with code 137

### ISSUE THREAD

**Issue by yisiliang** [vectorch-ai/ScaleLLM#38]
```
  scalellm:
    image: vectorchai/scalellm:latest
    hostname: scalellm
    container_name: scalellm
    ports:
      - 8888:8888
      - 9999:9999
    environment:
      - DEVICE=cpu
    volumes:
      - /Users/xxxx/yi/Yi-6B-Chat:/models/Yi-6B-Chat
    shm_size: 2g
    command: --model_path=/models/Yi-6B-Chat --model_id=01-ai/Yi-6B-Chat --model_type=Yi

```
the below scalellm docker runs with error :scalellm exited with code 137
```
scalellm          | ./entrypoint.sh: line 28:     7 Killed                  LD_LIBRARY_PATH=/app/lib:$LD_LIBRARY_PATH /app/bin/scalellm $ARGS "$@"
scalellm exited with code 137

```
